### PR TITLE
DRAFT: Add optional curl usage

### PR DESCRIPTION
**Pull request by marcomontevechi1**
This pull request is a draft with an initial idea about how to improve the usage.
Long story short is: it adds curl as an option (that is, the default operation still uses pure graphicsmagick) to grab the image and pass it as a Blob to GraphicsMagick, but I'm not sure if this is a good design. Another idea would be to simply create another driver (maybe AD**C**URL?) with just curl functionalities.

If any of these two options make sense, I can keep working on it until it's acceptable for merging. If not, I will close the PR.

Context is: me and Tomasz Brys were trying to integrate a Hikivision Speed Dome camera but were unable to find it's direct image or video stream URL, if there is any available at all. The camera does provide a web service with a video stream, but the url is hidden by some sort of redirection or something that I cannot fully understand. Trying to access it with graphicsmagick didn't work in any way we tried, always yielding:
```
2024/07/31 10:35:58.044 URLDriver:readImage: error reading URL=softIocPVA: Unable to access configuration file (delegates.mgk) reported by ../supportApp/GraphicsMagickSrc/magick/blob.c:1971 (GetConfigureBlob)
ics-ups-ioc-dev-449425 > dbpf $(PREFIX)cam1:Acquire 1
DBF_STRING:         "Acquire"
ics-ups-ioc-dev-449425 > 2024/07/31 10:36:01.316 URLDriver:readImage: error reading URL=softIocPVA: No decode delegate for this image format (/tmp/gm4WSJW3) reported by ../supportApp/GraphicsMagickSrc/magick/constitute.c:1535 (ReadImage)
```
 but curl managed to get the frame.

Since libCurl is fairly easy to manage, we added it to the driver. All curl options that I needed can be accessed as records and it is relatively easy to add new ones if needed. Only the HTTP authentication password and username options are in a TOML file instead of record, in order to not expose the credentials for everyone in the network.

libcurl and toml used documentation:

https://toruniina.github.io/toml11/docs/
https://curl.se/libcurl/c/ 

A typical acquisition with this module would be something like:

```
(...)
URLDriverConfig("$(PORT)", 0, 0)
(...)
iocInit()
dbpf $(PREFIX)cam1:URL1 "http://your_url" # Tell the driver which URL to look for
dbpf $(PREFIX)cam1:URLSelect 0        # Select URL 0 from the list of available URLs
dbpf $(PREFIX)cam1:ArrayCallbacks 1   # Selecting acquisition parameters and plugin configuration
dbpf $(PREFIX)image1:EnableCallbacks 1
dbpf $(PREFIX)image1:ArrayCallbacks 1
dbpf $(PREFIX)cam1:AcquireTime 2
dbpf $(PREFIX)cam1:AcquirePeriod 1
 
dbpf $(PREFIX)cam1:UseCurl 1          # Telling the driver to use Curl instead of GraphicsMagick
dbpf $(PREFIX)cam1:CurlOptHTTPAuth 2  # Telling the driver to use http authentication
dbpf $(PREFIX)cam1:CurlAuthFile "/tmp/file.toml"  # Telling the driver to look for authentication credentials in the file "/tmp/file.toml"
 
dbpf $(PREFIX)cam1:ImageMode_RBV 0
 
dbpf $(PREFIX)cam1:Acquire 1
```

### CODE REVIEW

**Comment by EmilioPeJu** [comment]
Hi @marcomontevechi1, Could you please provide some information about the problem you are having? I think manually running the curl command with `-D -' to dump headers could provide some hint on the cause of your problem, alternatively, a traffic capture (with e.g. wireshark) can help.

**Comment by EmilioPeJu** [comment]
I think it might be worth making libcurl an optional dependency, i.e. the curl specific code could be in a separate file that gets compiled only if `WITH_CURL` is set to yes in the `CONFIG_SITE` file (this also requires a little `#ifdef` magic in `URLDriver.cpp`, but should be minimal)

**Comment by marcomontevechi1** [comment]
@EmilioPeJu I think it's a good idea. In order to make that in the less invasive way I can think of I intend to put some class declaration stuff into a header file. Should that be another PR or can that be in this PR anyway?

**Comment by marcomontevechi1** [comment]
@EmilioPeJu I'm closing this pull request since I changed a lot about the overall structure in new branches. Will open a new one afterwards.

**Pull request closed without merging**
